#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000

#if defined(CONFIG_IDF_TARGET_ESP32S3)
//Platform: ESP32S3
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// 如果使用 Duplex I2S 模式，请注释下面一行
#define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_4
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_5
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_6
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_15
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_16

#else

#define AUDIO_I2S_GPIO_WS GPIO_NUM_4
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_6
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_7

#endif


#define BUILTIN_LED_GPIO        GPIO_NUM_48
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define TOUCH_BUTTON_GPIO       GPIO_NUM_47
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_40
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_39

#define DISPLAY_SDA_PIN GPIO_NUM_41
#define DISPLAY_SCL_PIN GPIO_NUM_42

#elif defined(CONFIG_IDF_TARGET_ESP32C6)
//Platform: ESP32C6
// ESP32C6 has only 1 I2S and only duplex mode is supported.
// Duplex mode reference : https://ccnphfhqs21z.feishu.cn/wiki/EH6wwrgvNiU7aykr7HgclP09nCh

#define AUDIO_OUTPUT_SAMPLE_RATE  AUDIO_INPUT_SAMPLE_RATE

#define AUDIO_I2S_GPIO_WS   GPIO_NUM_4       // WS for MIC, LRC for SPK
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_5       // SCK for MIC, BCLK for SPK
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_6       // SD for MIC
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_7       // DIN for SPK

#define BUILTIN_LED_GPIO        GPIO_NUM_8 //Updated for ESP32C6-WROOM-1 (48->8), Build-in LED
#define BOOT_BUTTON_GPIO        GPIO_NUM_9 //Updated for ESP32C6-WROOM-1 (0->9), Build-in Boot Button
#define TOUCH_BUTTON_GPIO       GPIO_NUM_21 //Updated for ESP32C6-WROOM-1 (47->21), NC
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_20 //Updated for ESP32C6-WROOM-1 (40->20)
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_19 //Updated for ESP32C6-WROOM-1 (39->19)

#define DISPLAY_SDA_PIN GPIO_NUM_10 //Updated for ESP32C6-WROOM-1 (41->10)
#define DISPLAY_SCL_PIN GPIO_NUM_11 //Updated for ESP32C6-WROOM-1 (42->11)

#else
#error "不支持 ESP32C6 以及 ESP32S3 以外的平台"
#endif

#define DISPLAY_WIDTH   128

#if CONFIG_OLED_SSD1306_128X32
#define DISPLAY_HEIGHT  32
#elif CONFIG_OLED_SSD1306_128X64
#define DISPLAY_HEIGHT  64
#elif CONFIG_OLED_SH1106_128X64
#define DISPLAY_HEIGHT  64
#define SH1106
#else
#error "未选择 OLED 屏幕类型"
#endif

#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true

#endif // _BOARD_CONFIG_H_
